---
name: Viewer Automation Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
      TEST_KEY: ${{ secrets.TEST_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven

      #- name: 'Set up Cloud SDK'
      #  uses: 'google-github-actions/setup-gcloud@v1'
      #  with:
      #    version: '>= 363.0.0'

      - name: Running test with Maven
        run: echo "$TEST_KEY"


