---
name: Manual Tests
on:
  #this allows to run manually
  workflow_dispatch:
    inputs:
      Env:
        description: Environment to run
        default: dev
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
      TEST_KEY: ${{ secrets.TEST_SECRET }}
      GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
      GCP_ACCOUNT: ${{ secrets.GCP_ACCOUNT}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Create gcp keyfile
        run: echo "$GCP_SERVICE_KEY" > tempkey.key

      - name: Setting GCP Key
        run: gcloud auth activate-service-account --key-file "tempkey.key"

      - name: Activate Accounts
        run: gcloud config set account $GCP_ACCOUNT

      - name: List Accounts
        run: gcloud auth list

      #- name: Running test with Maven
      #  run: mvn clean test -Denv=${{ inputs.Env }}
      - name: Run Manual Test
        run: echo "$TEST_KEY" | sed 's/./& /g'

      - name: Erasing tempkey file
        run: rm tempkey.key
